<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="views/assets/leafletlib/leaflet.css" type="text/css">
  <script src="views/assets/leafletlib/leaflet.js"></script>


  <title>Browse</title>
</head>

<body>



  <div class="container-lg" style="margin-top: 70px;">
    <h2 class="my-2 text-center">Search Chargepoints</h2>

    <form class="row g-3 mb-4" method="get" action='browseController.php'>


      <div class="input-group-md  col-md-6  d-flex align-items-end">
        <div class="input-group-text">
          <input class="form-check-input mt-0" type="radio" id='address' name='searchType' value="address" aria-label="Radio for address" checked onchange="changeForm()">
          <label for="address">
            <span>&emsp; Address</span></label>
        </div>


        <input type="text" list="addressesList" class="form-control" onkeyup="requestStreetAddressAjax(this.value)" name='streetAddress'>
        <datalist id="addressesList">
        </datalist>

      </div>

      <div class="input-group-md  col-md-6  d-flex align-items-end">
        <div class="input-group-text">
          <input class="form-check-input mt-0" type="radio" id='coordinates' name='searchType' value="coordinates" aria-label="Radio for address" onchange="changeForm()">
          <label for="coordinates">
            <span>&emsp; Coordinates</span></label>
        </div>
        <input type="text" aria-label="latitude" class="form-control" name='latitude' placeholder='latitude' disabled>
        <input type="text" aria-label="longitude" class="form-control" name='longitude' placeholder='longitude' disabled>
      </div>

      <div class="row my-2 d-flex justify-content-center align-items-center">
        <div class="input-group-md col-md-6 d-flex me-auto">
          <div class="input-group-text">
            <input class="form-check-input mt-0" type="checkbox" name='priceCheckbox' id='priceCheckbox' aria-label="Checkbox for following text input">
            <label for='priceCheckbox'>
              <span>&emsp; Price less than (gbp)</span> </label>
          </div>
          <input type="text" class="form-control" name='price' aria-label="Text input with checkbox">
        </div>

        <div class="input-group-md  col-md-6  d-flex mx-auto">
          <div class="input-group-text">
            <input class="form-check-input mt-0" type="checkbox" name='distanceCheckbox' value="" id='distanceCheckbox'>
            <label for="distanceCheckbox">
              <span>&emsp; Distance less than (km)</span></label>
          </div>
          <input type="text" class="form-control" name='distance' aria-label="Text input with checkbox" disabled>
        </div>

        <div class="col-md-auto my-2">
          <button type="submit" class="btn btn-primary" name='search'>Search</button>
        </div>
      </div>
    </form>
    <hr>

    <!-- ---------form end ---------------- -->
    <div id="map" style="height: 500px;"></div>

    <?php

    if (isset($_GET['searchType']) && $_GET['searchType'] == 'address') {
      foreach ($matchedAddresses as $address) {

        if ($address['id'] == 0)
          continue; //harcode it to not show address named "none"

    ?>

        <!-- One Address -->
        <div class="row">
          <div class="col-md-12">
            <h3><?php echo $address['streetAddress']; ?></h3>
            <p>Coordinates: <?php echo $address['latitude'] . ", " . $address['longitude']; ?></p>
            <p> Rate (per hour): <?php echo $address['rate']; ?> GBP</p>
            <?php

            //checking to see if the displayed address exists within the renter's subscriptions. If it exists, the button displayed will be disabled with the bootstrap disabled class
            $flag = 0;
            foreach ($renterSubscriptions as $renterSubscription)
              if ($address['id'] == $renterSubscription['addressId'] && $renterSubscription['status'] == 'active') {
                echo "<a class='btn btn-primary disabled' >Subscribed</a>";
                $flag = 1;
              }
            if ($flag == 0)
              echo "<a class='btn btn-primary' href='newSubscriptionController.php?address=" . $address['id'] . "'>Subscribe</a>";

            ?>

          </div>
        </div>
        <!-- /.row -->
        <hr>

      <?php
      }
    } elseif (isset($_GET['searchType']) && $_GET['searchType'] == 'coordinates') {

      foreach ($matchedAddresses as $address) {

        if ($address['id'] == 0)
          continue; //harcode it to not show address named "none"

        //var_dump($address);
      ?>

        <!-- One Address -->
        <div class="row">
          <div class="col-md-12">
            <h3><?php echo round($address['distance'], 2); ?> km away</h3>
            <p>Street Address: <?php echo $address['streetAddress']; ?></p>
            <p>Coordinates: <?php echo $address['latitude'] . ", " . $address['longitude']; ?></p>

            <?php
            if ($price != 0)
              echo "<p> Rate (per hour): <b>" . $address['rate'] . $price . " GBP</b></p>";
            else
              echo "<p> Rate (per hour): " . $address['rate'] . " GBP</p>";

            $flag = 0;
            foreach ($renterSubscriptions as $renterSubscription)
              if ($address['id'] == $renterSubscription['addressId']) {
                echo "<a class='btn btn-primary disabled' >Subscribed</a>";
                $flag = 1;
              }
            if ($flag == 0)
              echo "<a class='btn btn-primary' href='newSubscriptionController.php?address=" . $address['id'] . "'>Subscribe</a>";

            ?>

          </div>
        </div>
        <!-- /.row -->
        <hr>



    <?php
      }
    }
    ?>



    <div class="row">

      <div class="row align-items-center">
        <div class="col-xs-12 mb-3">
          <nav>
            <ul class="pagination">
              <?php
              if (isset($numberOfPages))
                for ($page = 1; $page <= $numberOfPages; $page++) {
                  //Get the current URL parameters
                  $params = $_GET;
                  //modify the 'page' parameter
                  $params['page'] = $page;
                  //build the new URL with modifies parameters
                  $newUrl = strtok($_SERVER["REQUEST_URI"], '?') . '?' . http_build_query($params);

                  echo "<li class='page-item'><a class='page-link' href = '" . $newUrl . "'>" . $page . "</a></li>";
                }
              ?>
            </ul>
          </nav>

        </div>
      </div>


    </div>


  </div>


  <script>
    var presentLatitude = 26.093364;
    var presentLongitude = 50.539511;
    var radius = 20;


    if (!navigator.geolocation) { //check to see if geolocation suppported
      alert('Geolocation is not supported');
    } else {
      document.getElementsByName('latitude')[0].value = 'Locating..';
      document.getElementsByName('longitude')[0].value = 'Locating..';
      //function to get the current position
      navigator.geolocation.getCurrentPosition(positionSucess, positionError);
    }

    //display the map

    //from term22023.html file
    var mymap = L.map('map').setView([presentLatitude, presentLongitude], 10);
    //adding map layer
    L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
      attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors',
      maxZoom: 18
    }).addTo(mymap);
    //Creating scale control - https://www.tutorialspoint.com/leafletjs/leafletjs_controls.htm
    L.control.scale().addTo(mymap);
    updateRadius(); // to display the chargepoints on the first view of the map

    //event will be triggered when map zoom changes or the map is moved
    mymap.addEventListener('moveend', function() {
      updateRadius();
    });

    //extra triggers
    /*   mymap.addEventListener('zoomend', function() {
      updateRadius();
    });

    mymap.addEventListener('mousemove', function() {
      updateRadius(event);
    });
    */
    // function to update the radius
    function updateRadius(event) {
      // Get the map edges
      var bounds = mymap.getBounds();
      //get map center
      const mapCenter = mymap.getCenter();

      // Calculate the distance from the center to the edge of the map
      coordinateDifference = mapCenter.distanceTo(bounds.getNorthWest());
      /* console.log("distance to edge:" + radius);
      console.log(mymap.getBounds().getNorthWest());
      console.log(mymap.getCenter()); */
      radius = haversineDistance(bounds.getNorthWest().lat, bounds.getNorthWest().lng, mapCenter.lat, mapCenter.lng);
      console.log("radius-" + radius);

      //if coordinates is selected, update the r in the form
      if (document.getElementById('coordinates').checked)
        document.getElementsByName('distance')[0].value = radius;

      requestMarkersAjax();
    }

    //function to return the distance between two points in km
    function haversineDistance(lat1, lng1, lat2, lng2) {
      const earthRadius = 6371000; // in meters

      const deltaLat = toRadians(lat2 - lat1);
      const deltaLng = toRadians(lng2 - lng1);

      const a = Math.sin(deltaLat / 2) * Math.sin(deltaLat / 2) +
        Math.cos(toRadians(lat1)) * Math.cos(toRadians(lat2)) *
        Math.sin(deltaLng / 2) * Math.sin(deltaLng / 2);

      const c = 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
      var distance = earthRadius * c;

      distance = distance / 1000; //convert meter to km
      return distance.toFixed(2); //round to 2 decimal places  https://stackoverflow.com/questions/11832914/how-to-round-to-at-most-2-decimal-places-if-necessary

    }

    function toRadians(degrees) {
      return degrees * Math.PI / 180;
    }


    function changeForm() {
      if (document.getElementById('address').checked) {
        document.getElementsByName('distanceCheckbox')[0].disabled = true;
        document.getElementsByName('distance')[0].value = "";
        document.getElementsByName('distance')[0].disabled = true;
        document.getElementsByName('distance')[0].required = false;
        document.getElementsByName('latitude')[0].disabled = true;
        document.getElementsByName('latitude')[0].value = "";
        document.getElementsByName('longitude')[0].disabled = true;
        document.getElementsByName('longitude')[0].value = "";
        document.getElementsByName('streetAddress')[0].disabled = false;
      } else if (document.getElementById('coordinates').checked) { //if coordinates checkbox is selected
        document.getElementsByName('distanceCheckbox')[0].disabled = false;
        document.getElementsByName('distance')[0].disabled = false;
        document.getElementsByName('distance')[0].required = true;
        document.getElementsByName('latitude')[0].disabled = false;
        document.getElementsByName('longitude')[0].disabled = false;
        document.getElementsByName('latitude')[0].disabled = false;
        document.getElementsByName('streetAddress')[0].disabled = true;
        document.getElementsByName('streetAddress')[0].value = "";

      }
    }


    function positionSucess(position) {
      //find the coordinates
      presentLatitude = position.coords.latitude;
      presentLongitude = position.coords.longitude;
      //change the coordinates in the form
      document.getElementsByName('latitude')[0].value = presentLatitude;
      document.getElementsByName('longitude')[0].value = presentLongitude;
      //update the map coordinates qith zoom 16
      mymap.setView([presentLatitude, presentLongitude], 16);
    }

    function positionError() {
      alert('Unable to retrieve your location');
      document.getElementsByName('latitude')[0].value = "";
      document.getElementsByName('longitude')[0].value = "";
    }

    //this function will take the user's query and send it to the server, and capture the response and call displayStreetAjaxOutput()
    function requestStreetAddressAjax(query) {
      if (query.length <= 2)
        return 0;

      var xhttp = new XMLHttpRequest();

      xhttp.open("GET", "browseController.php?searchType=address&streetAddress=" + query, true);
      xhttp.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
      xhttp.send();

      xhttp.onreadystatechange = function() {
        if (xhttp.readyState == 4 && xhttp.status == 200) {

          //capture ajax response which is json
          var response = xhttp.responseText;
          //send the response to the function that will display the suggestions
          displayStreetAjaxOutput(response);
        }
      };
    }

    function displayStreetAjaxOutput(response) {
      //convert the string sent by ajax to json format
      jsonObjResponse = JSON.parse(response);
      console.log(jsonObjResponse)

      //select the datalist element
      var dataList = document.getElementsByTagName('datalist')[0];
      //select all the options inside the datalist
      var dataListOptions = dataList.children;
      //add the list of street names to the datalist options
      for (let index = 0; index < jsonObjResponse.length; index++) {
        flag = 0;
        //loop through the options to see if the response to be added into the datalist already exists. if exists, change flag to 1
        for (let i = 0; i < dataListOptions.length; i++)
          if (dataListOptions[i].value == jsonObjResponse[index])
            flag = 1;

        //if flag=0, the response does not exist among the options, therefore add it to the datalist
        if (flag == 0)
          dataList.innerHTML += "<option value='" + jsonObjResponse[index] + "'></option>"
      }
    }


    function requestMarkersAjax() {
      var xhttp = new XMLHttpRequest();

      xhttp.open("GET", "browseController.php?searchType=coordinates&latitude=" + presentLatitude + "&longitude=" + presentLongitude + "&distance=" + radius, true);
      xhttp.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
      xhttp.send();

      xhttp.onreadystatechange = function() {
        if (xhttp.readyState == 4 && xhttp.status == 200) {

          //capture ajax response which is json
          var response = xhttp.responseText;
          //send the response to the function that will display the suggestions
          displayMarkersByAjax(response);
        }
      };
    }

    function displayMarkersByAjax(response) {
      jsonObjResponse = JSON.parse(response);

      //add the markers onto the map
      for (let index = 0; index < jsonObjResponse.length; index++)
        L.marker([jsonObjResponse[index].latitude, jsonObjResponse[index].longitude]).addTo(mymap).bindPopup(jsonObjResponse[index].latitude + "," + jsonObjResponse[index].longitude);


      console.log("########")
    }
  </script>
</body>


</html>