<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Browse</title>

</head>

<body>



  <div class="container-lg" style="margin-top: 70px;">
    <h2 class="my-2 text-center">Search Chargepoints</h2>

    <form class="row g-3 mb-4" action='browseController.php'>


      <div class="input-group-md  col-md-6  d-flex align-items-end">
        <div class="input-group-text">
          <input class="form-check-input mt-0" type="radio" id='address' name='searchType' value="address" aria-label="Radio for address" checked onchange="changeForm()">
          <label for="address">
            <span>&emsp; Address</span></label>
        </div>


        <input type="text" list="addressesList" class="form-control" onkeyup="requestAjax(this.value)" name='streetAddress'>
        <datalist id="addressesList">
        </datalist>

      </div>

      <div class="input-group-md  col-md-6  d-flex align-items-end">
        <div class="input-group-text">
          <input class="form-check-input mt-0" type="radio" id='coordinates' name='searchType' value="coordinates" aria-label="Radio for address" onchange="changeForm()">
          <label for="coordinates">
            <span>&emsp; Coordinates</span></label>
        </div>
        <input type="text" aria-label="latitude" class="form-control" name='latitude' placeholder='latitude' disabled>
        <input type="text" aria-label="longitude" class="form-control" name='longitude' placeholder='longitude' disabled>
      </div>

      <div class="row my-2 d-flex justify-content-center align-items-center">
        <div class="input-group-md col-md-6 d-flex me-auto">
          <div class="input-group-text">
            <input class="form-check-input mt-0" type="checkbox" name='pckboriceChex' id='priceCheckbox' aria-label="Checkbox for following text input">
            <label for='priceCheckbox'>
              <span>&emsp; Price less than (gbp)</span> </label>
          </div>
          <input type="text" class="form-control" name='price' aria-label="Text input with checkbox">
        </div>

        <div class="input-group-md  col-md-6  d-flex mx-auto">
          <div class="input-group-text">
            <input class="form-check-input mt-0" type="checkbox" name='distanceCheckbox' value="" id='distanceCheckbox'>
            <label for="distanceCheckbox">
              <span>&emsp; Distance less than (km)</span></label>
          </div>
          <input type="text" class="form-control" name='distance' aria-label="Text input with checkbox" disabled>
        </div>

        <div class="col-md-auto my-2">
          <button type="submit" class="btn btn-primary" name='search'>Search</button>
        </div>
      </div>
    </form>
    <hr>

    <!-- ---------form end ---------------- -->


    <?php

    if (isset($_GET['searchType']) && $_GET['searchType'] == 'address') {
      foreach ($matchedAddresses as $address) {

        if ($address['id'] == 0)
          continue; //harcode it to not show address named "none"

    ?>

        <!-- One Address -->
        <div class="row">
          <div class="col-md-12">
            <h3><?php echo $address['streetAddress']; ?></h3>
            <p>Coordinates: <?php echo $address['latitude'] . ", " . $address['longitude']; ?></p>
            <p> Rate (per hour): <?php echo $address['rate']; ?> GBP</p>
            <?php

            //checking to see if the displayed address exists within the renter's subscriptions. If it exists, the button displayed will be disabled with the bootstrap disabled class
            $flag = 0;
            foreach ($renterSubscriptions as $renterSubscription)
              if ($address['id'] == $renterSubscription['addressId'] && $renterSubscription['status'] == 'active') {
                echo "<a class='btn btn-primary disabled' >Subscribed</a>";
                $flag = 1;
              }
            if ($flag == 0)
              echo "<a class='btn btn-primary' href='newSubscriptionController.php?address=" . $address['id'] . "'>Subscribe</a>";

            ?>

          </div>
        </div>
        <!-- /.row -->
        <hr>

      <?php
      }
    } elseif (isset($_GET['searchType']) && $_GET['searchType'] == 'coordinates') {

      foreach ($matchedAddresses as $address) {

        if ($address['id'] == 0)
          continue; //harcode it to not show address named "none"

        //var_dump($address);
      ?>

        <!-- One Address -->
        <div class="row">
          <div class="col-md-12">
            <h3><?php echo round($address['distance'], 2); ?> km away</h3>
            <p>Street Address: <?php echo $address['streetAddress']; ?></p>
            <p>Coordinates: <?php echo $address['latitude'] . ", " . $address['longitude']; ?></p>

            <?php
            if ($price != 0)
              echo "<p> Rate (per hour): <b>" . $address['rate'] . $price . " GBP</b></p>";
            else
              echo "<p> Rate (per hour): " . $address['rate'] . " GBP</p>";

            $flag = 0;
            foreach ($renterSubscriptions as $renterSubscription)
              if ($address['id'] == $renterSubscription['addressId']) {
                echo "<a class='btn btn-primary disabled' >Subscribed</a>";
                $flag = 1;
              }
            if ($flag == 0)
              echo "<a class='btn btn-primary' href='newSubscriptionController.php?address=" . $address['id'] . "'>Subscribe</a>";

            ?>

          </div>
        </div>
        <!-- /.row -->
        <hr>



    <?php
      }
    }
    ?>



    <div class="row">

      <div class="row align-items-center">
        <div class="col-xs-12 mb-3">
          <nav>
            <ul class="pagination">
              <?php
              if (isset($numberOfPages))
                for ($page = 1; $page <= $numberOfPages; $page++) {
                  //Get the current URL parameters
                  $params = $_GET;
                  //modify the 'page' parameter
                  $params['page'] = $page;
                  //build the new URL with modifies parameters
                  $newUrl = strtok($_SERVER["REQUEST_URI"], '?') . '?' . http_build_query($params);

                  echo "<li class='page-item'><a class='page-link' href = '" . $newUrl . "'>" . $page . "</a></li>";
                }
              ?>
            </ul>
          </nav>

        </div>
      </div>


    </div>


  </div>


  <script>
    function changeForm() {
      if (document.getElementById('address').checked) {
        document.getElementsByName('distanceCheckbox')[0].disabled = true;
        document.getElementsByName('distance')[0].value = "";
        document.getElementsByName('distance')[0].disabled = true;
        document.getElementsByName('distance')[0].required = false;
        document.getElementsByName('latitude')[0].disabled = true;
        document.getElementsByName('latitude')[0].value = "";
        document.getElementsByName('longitude')[0].disabled = true;
        document.getElementsByName('longitude')[0].value = "";
        document.getElementsByName('streetAddress')[0].disabled = false;
      } else if (document.getElementById('coordinates').checked) {
        document.getElementsByName('distanceCheckbox')[0].disabled = false;
        document.getElementsByName('distance')[0].disabled = false;
        document.getElementsByName('distance')[0].required = true;
        document.getElementsByName('latitude')[0].disabled = false;
        document.getElementsByName('longitude')[0].disabled = false;
        document.getElementsByName('latitude')[0].disabled = false;
        document.getElementsByName('streetAddress')[0].disabled = true;
        document.getElementsByName('streetAddress')[0].value = "";
      }
    }

    //this function will take the user's query and send it to the server, and capture the response and call displayAjaxOutput()
    function requestAjax(query) {

      if (query.length <= 2)
        return 0;


      var xhttp = new XMLHttpRequest();

      xhttp.open("GET", "browseController.php?searchType=address&streetAddress=" + query, true);
      xhttp.setRequestHeader('X-Requested-With', 'XMLHttpRequest');
      xhttp.send();

      xhttp.onreadystatechange = function() {
        if (xhttp.readyState == 4 && xhttp.status == 200) {

          //capture ajax response which is json
          var response = xhttp.responseText;
          //send the response to the function that will display the suggestions
          displayAjaxOutput(response);
        }
      };


    }

    function displayAjaxOutput(response) {
      //convert the string sent by ajax to json format
      jsonObjResponse = JSON.parse(response);
      //      console.log(jsonObjResponse)

      //select the datalist element
      var dataList = document.getElementsByTagName('datalist')[0];
      //select all the options inside the datalist
      var dataListOptions = dataList.children;
      //add the list of street names to the datalist options
      for (let index = 0; index < jsonObjResponse.length; index++) {
        flag = 0;
        //loop through the options to see if the response to be added into the datalist already exists. if exists, change flag to 1
        for (let i = 0; i < dataListOptions.length; i++)
          if (dataListOptions[i].value == jsonObjResponse[index])
            flag = 1;

        //if flag=0, the response does not exist among the options, therefore add it to the datalist
        if (flag == 0)
          dataList.innerHTML += "<option value='" + jsonObjResponse[index] + "'>"

      }

    }
  </script>
</body>


</html>