<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">

  <link rel="stylesheet" href="css/leafletlib/leaflet.css" type="text/css">
  <script src="js/leafletlib/leaflet.js"></script>


  <title>Browse</title>
</head>

<body>



  <div class="container-lg" style="margin-top: 70px;">
    <h2 class="my-2 text-center">Search Chargepoints</h2>

    <form class="row g-3 mb-4" method="get" action='browseController.php'>


      <div class="input-group-md  col-md-6  d-flex align-items-end">
        <div class="input-group-text">
          <input class="form-check-input mt-0" type="radio" id='address' name='searchType' value="address" aria-label="Radio for address" checked onchange="changeForm()">
          <label for="address">
            <span>&emsp; Address</span></label>
        </div>


        <input type="text" list="addressesList" class="form-control" onkeyup="requestStreetAddressAjax(this.value)" name='streetAddress'>
        <datalist id="addressesList">
        </datalist>

      </div>

      <div class="input-group-md  col-md-6  d-flex align-items-end">
        <div class="input-group-text">
          <input class="form-check-input mt-0" type="radio" id='coordinates' name='searchType' value="coordinates" aria-label="Radio for address" onchange="changeForm()">
          <label for="coordinates">
            <span>&emsp; Coordinates</span></label>
        </div>
        <input type="text" aria-label="latitude" class="form-control" name='latitude' placeholder='latitude' disabled>
        <input type="text" aria-label="longitude" class="form-control" name='longitude' placeholder='longitude' disabled>
      </div>

      <div class="row my-2 d-flex justify-content-center align-items-center">
        <div class="input-group-md col-md-6 d-flex me-auto">
          <div class="input-group-text">
            <input class="form-check-input mt-0" type="checkbox" name='priceCheckbox' id='priceCheckbox' aria-label="Checkbox for following text input">
            <label for='priceCheckbox'>
              <span>&emsp; Price less than (gbp)</span> </label>
          </div>
          <input type="text" class="form-control" name='price' aria-label="Text input with checkbox">
        </div>

        <div class="input-group-md  col-md-6  d-flex mx-auto">
          <div class="input-group-text">
            <input class="form-check-input mt-0" type="checkbox" name='distanceCheckbox' value="" id='distanceCheckbox'>
            <label for="distanceCheckbox">
              <span>&emsp; Distance less than (km)</span></label>
          </div>
          <input type="text" class="form-control" name='distance' aria-label="Text input with checkbox" disabled>
        </div>

        <div class="col-md-auto my-2">
          <button type="submit" class="btn btn-primary" name='search'>Search</button>
        </div>
      </div>
    </form>
    <hr>

    <!-- ---------form end ---------------- -->
    <div id="map" style="height: 500px;"></div>
    <!-- ------------map end----------- -->
    <?php
    if (isset($_GET['searchType']) && $_GET['searchType'] == 'address') {
      foreach ($matchedAddresses as $address) {

        if ($address['id'] == 0)
          continue; //harcode it to not show address named "none"

    ?>

        <!-- One Address -->
        <div class="row mt-2">
          <div class="col-md-12">
            <h3><?php echo $address['streetAddress']; ?></h3>
            <p>Coordinates: <?php echo $address['latitude'] . ", " . $address['longitude']; ?></p>
            <p> Rate (per hour): <?php echo $address['rate']; ?> GBP</p>
            <?php

            //checking to see if the displayed address exists within the renter's subscriptions. If it exists, the button displayed will be disabled with the bootstrap disabled class
            $flag = 0;
            foreach ($renterSubscriptions as $renterSubscription)
              if ($address['id'] == $renterSubscription['addressId'] && $renterSubscription['status'] == 'renting') {
                echo "<a class='btn btn-primary disabled' >Subscribed</a>";
                $flag = 1;
              }

            if ($flag == 0)
              echo "<a class='btn btn-primary' href='newSubscriptionController.php?address=" . $address['id'] . "'>Subscribe</a>";

            ?>

          </div>
        </div>
        <!-- /.row -->
        <hr>

      <?php
      }
    } elseif (isset($_GET['searchType']) && $_GET['searchType'] == 'coordinates') {

      foreach ($matchedAddresses as $address) {

        if ($address['id'] == 0)
          continue; //harcode it to not show address named "none"

        //var_dump($address);
      ?>

        <!-- One Address -->
        <div class="row">
          <div class="col-md-12">
            <h3><?php echo round($address['distance'], 2); ?> km away</h3>
            <p>Street Address: <?php echo $address['streetAddress']; ?></p>
            <p>Coordinates: <?php echo $address['latitude'] . ", " . $address['longitude']; ?></p>

            <?php
            if ($price != 0)
              echo "<p> Rate (per hour): <b>" . $address['rate'] . $price . " GBP</b></p>";
            else
              echo "<p> Rate (per hour): " . $address['rate'] . " GBP</p>";

            $flag = 0;
            foreach ($renterSubscriptions as $renterSubscription)
              if ($address['id'] == $renterSubscription['addressId'] && $renterSubscription['status'] == 'renting') {
                echo "<a class='btn btn-primary disabled' >Subscribed</a>";
                $flag = 1;
              }
            if ($flag == 0)
              echo "<a class='btn btn-primary' href='newSubscriptionController.php?address=" . $address['id'] . "'>Subscribe</a>";

            ?>

          </div>
        </div>
        <!-- /.row -->
        <hr>



    <?php
      }
    }
    ?>



    <div class="row">

      <div class="row align-items-center">
        <div class="col-xs-12 mb-3">
          <nav>
            <ul class="pagination">
              <?php
              if (isset($numberOfPages))
                for ($page = 1; $page <= $numberOfPages; $page++) {
                  //Get the current URL parameters
                  $params = $_GET;
                  //modify the 'page' parameter
                  $params['page'] = $page;
                  //build the new URL with modifies parameters
                  $newUrl = strtok($_SERVER["REQUEST_URI"], '?') . '?' . http_build_query($params);

                  echo "<li class='page-item'><a class='page-link' href = '" . $newUrl . "'>" . $page . "</a></li>";
                }
              ?>
            </ul>
          </nav>

        </div>
      </div>


    </div>


  </div>


  <script src="js/browseScript.js"> </script>
</body>


</html>