<!DOCTYPE html>
<html lang="en" dir="ltr">

<head>
	<meta charset="utf-8">
	<title>Borrow my Charger</title>
	<link rel="stylesheet" href="views/css/loginstylesheet.css">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>

<body>
	<div class="wrapper">
		<div class="title-text">
			<div class="title login">
				Login Form
			</div>
			<div class="title signup">
				Signup Form
			</div>
		</div>
		<div class="form-container">
			<div class="slide-controls">
				<input type="radio" name="slide" id="login" checked>
				<input type="radio" name="slide" id="signup">
				<label for="login" class="slide login">Login</label>
				<label for="signup" class="slide signup">Signup</label>
				<div class="slider-tab"></div>
			</div>
			<div class="form-inner">
				<form method='post' action="credentialController.php" class="login">
					<div class="field">
						<input type="text" name="email" placeholder="Email Address" required>
					</div>
					<div class="field">
						<input name="password" type="password" placeholder="Password" required>
					</div>
					<div class="field btn">
						<div class="btn-layer"></div>
						<input type="submit" name='submit' value="Login">
					</div>
					<div class="signup-link">
						<!-- Not a member? <a href="">Signup now</a> -->
						<?php
						if (isset($error)) {
							echo $error;
						}
						?>
					</div>
				</form>
				<form method='post' action="credentialController.php" class="signup">
					<div>
						<div class="field">
							<input type="text" name='name' placeholder="Name" required>
						</div>
						<div class="field">
							<input type="text" name='email' placeholder="Email Address" required>
						</div>
						<div class="field">
							<input type="password" name='password' placeholder="Password" required>
						</div>
						<div class="field">
							<input type="password" name='password' placeholder="Password" required>
						</div>
						<div class="field">
							selection input <br>
							if true, required street address, latitude, longtitude, price per KWh
							<br><br><br><br>
							dsd
						</div>
						<!-- <div class="field">
						<input type="password" placeholder="Confirm password" required>
					</div> -->
					</div>
					<div class="field btn">
						<div class="btn-layer"></div>
						<input type="submit" name='submit' value="Signup">
					</div>
				</form>
			</div>
		</div>
	</div>
	<script>
		//below is for styling
		const loginText = document.querySelector(".title-text .login");
		const loginForm = document.querySelector("form.login");
		const loginBtn = document.querySelector("label.login");
		const signupBtn = document.querySelector("label.signup");
		const signupLink = document.querySelector("form .signup-link a");
		signupBtn.onclick = (() => {
			loginForm.style.marginLeft = "-50%";
			loginText.style.marginLeft = "-50%";
		});
		loginBtn.onclick = (() => {
			loginForm.style.marginLeft = "0%";
			loginText.style.marginLeft = "0%";
		});
		signupLink.onclick = (() => {
			signupBtn.click();
			return false;
		});
	</script>
</body>

</html>