<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>New Subscription</title>
</head>

<body>

  <div class="container-lg" style="margin-top: 70px;">
    <h2 class="my-3 text-center">Subscribe to a Chargepoint</h2>

    <form class="row g-3" id="myForm" action="newSubscriptionController.php">
      <div class="col-md-4">
        <label for="date" class="form-label">Start Date</label>
        <input type="date" name='date' class="form-control" id="date" min="<?php echo date('Y-m-d'); ?>" onchange="setMinTime()" required>
      </div>
      <div class="col-md-4 col-6">
        <label for="startTime" class="form-label">Start Time</label>
        <input type="time" name='startTime' class="form-control" id="startTime" required onchange="verifyTime()">
      </div>
      <div class="col-md-4 col-6">
        <label for="endTime" class="form-label">End Time</label>
        <input type="time" name='endTime' class="form-control" id="endTime" required>
      </div>
      <span class="col-md-4"></span>
      <span class="col-md-8 help-block text-light-emphasis">End time must be less than 3 hours after start time</span>

      <hr>

      <h5 class="my-2 text-center">Booked Timings</h5>
      <div class="row d-flex">
        <?php
        foreach ($occupiedSlots as $slot) {
        ?>

          <div class="col-md-3 col-6">
            <p><?php echo $slot['startDate'] . "  " . $slot['startTime'] . "-" . $slot['endTime']; ?></p>
          </div>


        <?php
        }
        ?>


      </div>
      <hr>

      <div class="col-12">
        <label for="staticStreet" class="form-label">Address</label>
        <div class="col-sm-10">
          <input class="form-control" type="text" id="staticStreet" aria-label="Disabled input example" value="<?php echo $addressRow['streetAddress']; ?>" disabled readonly>
        </div>
      </div>


      <div class="col-12">
        <label for="staticCoordinate" class="form-label">Coordinates</label>
        <div class="col-sm-10">
          <input class="form-control" type="text" id="staticCoordinate" aria-label="Disabled input example" value='<?php echo $addressRow['latitude'] . ", " . $addressRow['longitude']; ?>' disabled readonly>
        </div>
      </div>

      <div class="col-12">
        <label for="staticPrice" class="form-label">Charge Per Hour</label>
        <div class="col-sm-10">
          <input class="form-control" type="text" id="staticPrice"  value="<?php echo $addressRow['rate']; ?> GBP" disabled readonly>
        </div>
      </div>

      <input type='hidden' name='addressIdHidden' value='<?php echo $_GET['address']; ?>'>

      <div class="col-12">
        <button type="submit" name='submitForm' class="btn btn-primary">Subscribe</button>
      </div>
    </form>

  </div>
  <?php

  if (isset($error)) {
    echo "<script>alert('$error');</script>";
  }


  ?>
</body>
<script src="js/newSubscriptionScript.js"> </script>

</html>