<!doctype html>
<html lang="en">

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Profile</title>
  <link href="views/assets/dist/css/bootstrap.min.css" rel="stylesheet">
  <link href="loginForm.css" rel="stylesheet">
  <style>
    #register {
      margin-top: 135px;
      margin-left: auto;
      margin-right: auto;
      margin-bottom: 70px;
      width: 700px;
      padding: 80px;
      padding-bottom: 25px;
      padding-top: 40px;
      border-radius: 5%;
      border: 5px solid black;
    }

    .register {
      font-size: 40px;
    }

    .form-control {
      font-size: 18px;
      font-weight: bolder;
    }

    .form-control::placeholder {
      font-weight: 20;
    }
  </style>
</head>

<body>
  <br /><br /> <br />
  <div class="container">
    <main class="form-signin w-100 m-auto">
      <div class="border border-secondary border-2 rounded">
        <form id='profileForm' onSubmit="return checkeditedInputs();" action='updateProfile.php' method='post' class="m-4" enctype="multipart/form-data">
          <h1 class="h3 mb-3 fw-normal text-center">Profile</h1>

          <div class="mx-auto">
            <img src='views/assets/image/<?php echo $profile_pic; ?>' class='profile-pic img-fluid w-100 border border-secondary border-2 rounded ' alt='profilepic'>
          </div>
          <input type="file" name="picfile" id='fileUpload' /><span> (images<=5MB) </span><br><br>

              <div class="mb-2">
                <label for="name" class="form-label">Name</label>
                <input class="form-control" id='name' type="text" name='name' size='50' value='<?php echo htmlspecialchars("$name"); ?>' aria-label="readonly input example" readonly>
              </div>

              <div class="mb-2">
                <label for="email" class="form-label">Email</label>
                <input class="form-control" id='email' type="text" name='email' size='50' value='<?php echo "$email"; ?>' aria-label="readonly input example" readonly>
              </div>

              <div class="mb-2">
                <label for="street" class="form-label">Street Address</label>
                <input class="form-control" id='street' type="text" name='street' size='50' value='<?php echo htmlspecialchars("$street"); ?>' aria-label="readonly input example" readonly>
              </div>

              <div class="mb-2">
                <label for="coordinates" class="form-label">Coordinates</label>
                <input class="form-control" id='coordinates' type="text" name='coordinates' size='50' value='<?php echo "$latitude" . "$longitude"; ?>' aria-label="readonly input example" readonly>
              </div>

              <div class="mb-2">
                <label for="status" class="form-label">Name</label>
                <input class="form-control" id='status' type="text" name='status' size='50' value='<?php
                                                                                                    if ($isOwner)
                                                                                                      echo "Owner";
                                                                                                    else
                                                                                                      echo "Renter";
                                                                                                    ?>' aria-label="readonly input example" readonly>
              </div>


              <input class="w-100 btn btn-lg btn-primary mt-2" type='submit' name='edit_user' value='Edit'>
        </form>
      </div>
    </main>
  </div>
  <?php

  $error = null;
  extract($_GET);
  if ($error == 1) {
    echo "<script> alert('File could not be uploaded'); </script>";
  } elseif ($error == 3) {
    echo "<script> alert('Database error :('); </script>";
  }
  ?>
</body>

</html>