<!doctype html>
<html lang="en">

<head>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Profile</title>
  <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet">
  <style>
    .form-control {
      font-size: 18px;
      font-weight: bolder;
    }

    .form-control::placeholder {
      font-weight: 20;
    }

    .profile-picSizeOverride {
      max-width: 300px !important;
      max-height: 300px !important;
    }
  </style>
</head>

<body>
  <br /><br /> <br />
  <div class="container ">
    <main class="form-signin w-100 m-auto">
      <div class="border border-secondary border-2 rounded">
        <form id='profileForm' action='profileController.php' method='post' class="m-4" enctype="multipart/form-data">
          <h1 class="h3 mb-3 fw-normal text-center">Profile</h1>

          <div class="mx-auto text-center">
            <img src='image/<?php echo $profile_pic; ?>' class='profile-pic img-fluid  border border-secondary border-2 rounded profile-picSizeOverride' alt='profilepic'>
          </div>
          <!--           <div class="mx-auto d-block"> -->
          <input type="file" name="picfile" id='fileUpload' /><span> (images<=5MB) </span>
              <!--           </div> -->
              <br><br>
              <div class="mb-2">
                <label for="name" class="form-label">Name</label>
                <input class="form-control" id='name' type="text" name='name' size='50' value='<?php echo htmlspecialchars("$name"); ?>' aria-label="readonly input example" readonly>
              </div>

              <div class="mb-2">
                <label for="email" class="form-label">Email</label>
                <input class="form-control" id='email' type="text" name='email' size='50' value='<?php echo "$email"; ?>' aria-label="readonly input example" readonly>
              </div>

              <div class="mb-2">
                <label for="street" class="form-label">Street Address</label>
                <input class="form-control" id='street' type="text" name='street' size='50' value='<?php echo htmlspecialchars("$streetName"); ?>' aria-label="readonly input example" readonly>
              </div>

              <div class="mb-2">
                <label for="coordinates" class="form-label">Coordinates</label>
                <input class="form-control" id='coordinates' type="text" name='coordinates' size='50' value='<?php echo $coordinates; ?>' aria-label="readonly input example" readonly>
              </div>

              <div class="mb-2">
                <label for="status" class="form-label">User Type</label>
                <input class="form-control" id='status' type="text" name='status' size='50' value='<?php
                                                                                                    if ($userProfile['isOwner'] == "true")
                                                                                                      echo "Owner";
                                                                                                    else
                                                                                                      echo "Renter";
                                                                                                    ?>' aria-label="readonly input example" readonly>
              </div>


              <input class="w-100 btn btn-lg btn-primary mt-2" type='submit' name='edit_user' value='Edit'>
        </form>
      </div>
    </main>
  </div>
  <script>
    <?php
    if (isset($error))
      echo "alert(\"" . $error . "\");";
    ?>
  </script>
</body>


</html>