<head>
  <link href="css/bootstrap/bootstrap.min.css" rel="stylesheet">
</head>
<nav class="navbar navbar-expand-lg bg-primary fixed-top border border-dark-subtle border-top-0 border-end-0 border-start-0 d-flex" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="index.php">
      <img src="image/logo1.png" alt="Logo" width="40" height="34" class="d-inline-block">
      HCF</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="browseController.php">Browse</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="manageSubscriptionController.php">Subscriptions</a>
        </li>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="profileController.php">Profile</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="logout.php">Logout</a>
        </li>
      </ul>

    </div>
  </div>

</nav>

<script src="js/bootstrap/bootstrap.bundle.min.js"></script>